include:
  - proxy.yaml 
services:
  web:
    image: $DOCKER_REGISTRY/$REGISTRY_ID/$IMAGE_NAME:${CI_COMMIT_SHORT_SHA}
    env_file:
      - .env
      - /etc/myapp/db.conf
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.5
  
